### ISSUE TITLE
Cannot call const-ref to function

### ISSUE THREAD

**Issue by dermojo** [Naios/function2#12]
@Naios 

-----

### Expected Behavior

Taking functions by const-ref and calling them should be possible (same as std::function).

### Actual Behavior

Calling a const-ref fu2::function fails to compile (same for unique_function and function_view). Output from GCC:
```
error: no match for call to ‘(fu2::function<void()> {aka const fu2::abi_300::detail::function<fu2::abi_300::detail::config<true, true, 16ul>, fu2::abi_300::detail::property<true, false, void()> >}) ()’
    fun();
        ^
In file included from fu2_constref.cpp:1:0:
function2-3.0.0/include/function2/function2.hpp:595:9: note: candidate: Ret fu2::abi_300::detail::type_erasure::invocation_table::operator_impl<Index, fu2::abi_300::detail::function<Config, Property>, Ret(Args ...)>::operator()(Args ...) [with long unsigned int Index = 0ul; Config = fu2::abi_300::detail::config<true, true, 16ul>; Property = fu2::abi_300::detail::property<true, false, void()>; Ret = void; Args = {}] <near match>
     Ret operator()(Args... args) CONST VOLATILE OVL_REF {                      \

```

### Steps to Reproduce

Sample code:
```
#include <function2/function2.hpp>
#include <iostream>

static void call(const fu2::function<void()>& fun)
{
   fun();
}

int main()
{
   fu2::function<void()> fun = [] { std::cout << "Hello World\n"; };
   call(fun);
   return 0;
}
```

### Your Environment

- OS: Linux
- Compiler and version: tested with GCC 5.4 & 6.3, Clang 4/5/6
Tested with 2.3.0, 3.0.0 and current master.

**Comment by Naios** [comment]
Thanks for your issue report. I will take a look into this in the next few days.

**Comment by Naios** [comment]
I took a look into this and the behaviour is as intended.

function2 basically doesn't allow to call a non const signature from a const context,
in order to ensure qualifier correct invocation.
`std::function` for instance allows this, because it doesn't invoke the underlying callable object in a qualifier correct way, which could violate thread safety guarantess and the mutability of a const object itself,
