### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by FrankHB** [Naios/function2#16]
@Naios

```
fu2::function<void(int, float) const>
// Return type ~^   ^     ^     ^
// Arguments ~~~~~~~|~~~~~|     ^
// Qualifier ~~~~~~~~~~~~~~~~~~~|
```

"Arguments" seems the wrong term, and it should be "parameters". They are indeed parts of an argument (`void(int, float) const`) in the sense of type arguments of the template `function`, but not the function arguments in the function call syntax used in client code. It seems incorrect to put it next to "return type".

**Comment by Naios** [comment]
Thanks for your bug report.
It was fixed due to version v3.1.0.
