### ISSUE TITLE
C++17 noexcept support

### ISSUE THREAD

**Issue by bebuch** [Naios/function2#17]
With C++17 the `noexcept`-specification became part of the function type. Do you have any support for it? The documentation doesn't mention it, but I found the specifier in your source.

It would be great if function2 would support `noexcept` for function types. Besides move-only callables this is the second big leak of `std::function`. (https://wg21.link/p0045 tries to fix this.)

If your current implementation already supports `noexcept`, it would be nice if you could add in the documentation in which way. Otherwise it would be nice if you would add this to the todos for the next version.

Thanks for the great library by the way! 😊

**Comment by Naios** [comment]
The support for the C++17 `noexcept` qualifier was added in version [3.1.0](https://github.com/Naios/function2/releases/tag/3.1.0) already, see #15.
The qualifier should work automatically out of the box if C++17 is enabled,
see the [corresponding unit tests](https://github.com/Naios/function2/blob/ce2ed01f6d0d3133d366226f96ce2902c1ca814e/test/noexcept-test.cpp#L26-L37) for a usage example.
But you are right, this feature isn't documented in the readme yet, I'll fix this soon.
