### ISSUE TITLE
Cannot compile with Clang with exceptions turned off

### ISSUE THREAD

**Issue by Rajveer86** [Naios/function2#5]
I would like to use a self-defined version of unique_function using function_base which doesn't throw an exception, as I would prefer to use Clang's default setting of no exceptions. However, as soon as I include the header file, Clang parses it and complains that throw() isn't supported.

Adding the -fdelayed-template-parsing flag to Clang works, however if possible I would rather not use WIP (and non-standard, according to [this answer](http://stackoverflow.com/questions/9303843/clang-vs-msvc-treatment-of-template-function-prototypes)) flags.

Is it possible to modify the header file so that it only exposes exception code if exceptions are turned on?

**Comment by Naios** [comment]
Thanks for the catch and the suggestion, I will add a travis build with exceptions disabled to ensure the exceptions disabled functionality.

**Comment by Naios** [comment]
I need to replace the `Catch` testsuite by `gtest `because `Catch` requires exceptions enabled.

**Comment by Rajveer86** [comment]
If this is something you are still open to doing considering it will require you to change your test environment then please take your time. I'm in no rush for this so don't worry about doing it as soon as possible!

**Comment by Naios** [comment]
I also added a no exceptions build to travis](https://travis-ci.org/Naios/function2/jobs/112428336) to ensure further regressions.

**Comment by Rajveer86** [comment]
This now works perfectly, thank you!
