### ISSUE TITLE
Compile time bug with noexcept specifier

### ISSUE THREAD

**Issue by MBkkt** [Naios/function2#50]
@Naios 

Cannot use noexcept specifier.
Looks like a compile time bug. I think something should be sfinae but its not

-----

### Commit Hash

last, 035bec21533f484c1b5dd8dd0380109ea431f6a1

### Expected Behavior

Should compile

### Actual Behavior

Don't compile

### Steps to Reproduce

[See godbolt
](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAMzSrgAyeAyYAHI%2BAEaYxBL%2BpAAOqAqETgwe3r4B0ilpjgKh4VEssfFciXaYDhlCBEzEBFk%2BfmYAbLaY9oUM9Y0ExZExcQm2DU0tOR3jA0Ol5QkAlLaoXsTI7BwmGgCC5v5hyN5YANTmZggEBEkKIAD098RMAO4AdMCECF7RXkobskYBDeaBY9wiTCcCnuVC8DFqAjM9xYTAUBDi9yOJ0wMLhCIYSNh8N6ZjeCCSSQuO32ezRxC8DlOAGlMABrc4Adise1OzLZ1C8ZhAIDheAAjl5MAB9In4kz%2BNwAN1QeHQECWpwYqEwqk2SQI8uwGq1Or1Bq5Jg5ABFqbyWayIPbzO1ncbtbrMPrLVZrba%2BaznadUEk4kwiMR5VbHWzna7Ne6zd7LTa9sn5dyabs6QyCKddpyfTb/BnqdnGRZ6QhTiA8wW/TqkrQ8MhCKcK14ENGAx1A6y3abPbma6yY1y0ehhSxUIrMBA%2B8m676ef7TiOA8XqWmN6m9mFcyiwuq68veUwvERTlRzv4radx5OmCOpaKJZh5W52whDV2kwBWKy/lG/Yevqi42taSzppu1ocCstCcL%2BvB%2BBwWikKgnBuNY1h3msGyYOcZj%2BDwpAEJosErKyIBmBo%2BicJISFkWhnC8HcNGkShsGkHAsBIKCSR0HE5CUHxAnxMAXBmFwfB0OixB3BA0SMdEYSNAAnpwxGgmwggAPIMLQ6kcaQWAokY4hGfgxA1I4M53EZOo1OeWzEXu3SMU20TPMQqkeFgjEEMQeAsBpnFUAYwAKAAangmAvDpIbIcR/CCCIYjsFIMiCIoKjqEZuhSQYRgoFhlj6Hg0R3JAKzBr0dksd01kZC4DDuJ4rR6CEYTDGUoxSfk6QCFMfh9akA0MPMIwVF0PR1BMzRtTkUnVPi/RNBNPVTWiAxDXoW1rV1Cy9SsCi4ZsegBZgzmcfBHCIaQyGoehHCqAAHO0AC07SSKcwDIMgpwSW8XCnBAmGWNYpCnLghAkARRGQx4LD8fQxBw1wSy8OxWhLBRVE0Td9H3YxT0sSAbFkSs3GICAaw3OeQkQCJKMQmwnCvR9X0/X9AOksRmD4OGqp6MlwiiOIGUi9laiMflpAvM8SQhXBCEMUZT06eeSTnkGV7s5932/f9gPA6DqBI6JaMYyRFO49RtEcITD28CTthk9bHGUzA1NoFg0PhgzND0MwrPcLwIupeL0iS0o0t5VR%2BiGMYJU2MtvTNa12R%2BP4v6kJ1JSTWM/W9Dt2fJKNvTrYslTTY1AirfNmcBDnqezXMB0F9Xe0N%2B1pdd5XvX%2BMdp1bJuhFYl4ZwXFcNx3I8zzvJ8BDfL8/xoIIQIgmb4KQqkuLEhkSIomiGLj1ge/4oSeIkmSFJUjuWYBTmK5Jsu9oCkKIoMOKkoylfGTvsqVU6pDTAUTBaJc%2BZ/Q/h7B0UBg4kwQLtDGDoQYQzPHDJGaBLpYHxgHF6cBKZ9i%2Bm3JmMsuZ8wIKLCWWkj9yyVmrLWF%2BkCGxNhbLmT8WDexwNAsOUcFh7wgCnDOOckFrRgT9PaVcMYSFbmobsPcpwDwMCPEw3kp5zyoEvNeW8AiURPhfJKd8n5vxOgtP%2BEwgEjwmhArmShyZIIyJgsrW6qtHoYWTjhdYmw4ZmExjbUglE7YE1cc7ZirtyYey4l7CAvEzbI0EhQRmcTRIgHEpJaStBZLyUUkZZSzBvIhVIFpIEekDKMRMoncyqFLKNVsoxByyAnKFNcjdVCHkvI%2BQwFsVCAUgpKz4OFKKMU4oJUKeHMW6Uo6yClrlVCugzAJyKqYcGpUPKVXVGhfUGQ6o13xOnHaUk87dSrmXAoGQDmnLGv3TaDUVpzQuS3Ouc1rm7XuQtYasx9r5w2hIIeXj2ALIuldZxd0nZMWem9fWXMja8xBmDKwpUoYC1hgcBZpxEbxNRqiq2WNyIBLxvbR2xMwmsXdtjZxviiZqzCbinGpAZxySapIIAA%3D)
### Your Environment

- OS: Arch Linux
- Compiler and version: gcc 12.1

**Comment by Naios** [comment]
Your issue is missing a minimalistic reproducible example: I cannot guess from vague chosen identifiers like "Bruh" or "Kek" what is the behaviour you are expecting from the library and whats not working as intended.
Provide an example with no indirections (over `unique_ptr` and constructors) please.

Note that `noexcept` in function definitions only works on C++17 and above (due to limitations of earlier standards).

**Comment by MBkkt** [comment]
@Naios 
I think its simple, and you and you are nitpicking, but
https://godbolt.org/z/bfYW539YW

**Comment by MBkkt** [comment]
For some reason GCC starts with 10 or 11 (forgot) first try to call function ctor instead of move ctor

**Comment by MBkkt** [comment]
Make it better and permanent [link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEEgAcpAAOqAqETgwe3r7%2ByanpAiFhkSwxcVyJdpgOGUIETMQEWT5%2BXLaY9o4CdQ0ERRHRsXoK9Y3NOW0jvf0lZRIAlLaoXsTI7BwmGgCC5gDMocjeWADU5mYIBARJCiAA9LfETADuAHTAhAheUV5Kq7KMBBeaBYt3CTCcCluVC8DBqAjMtxYTBGsVuByOmChMLhDAR0NhXVxLwQSSSZ02O22I2IXgcxwAYtiiMQ6iQmMBMKcAOxWbbHY6YVRJWh4ZCEBlMkisx4c6heMwgEAwvAARy8mAA%2BvicSZdm4AG6oPDoCDzY4MVCCtZJAi67Bmi1WzA27lWLkAEQp/MZBKlzPZmAgPocfrZHPMADZIw7LaprQRXSYPRSk57drzKVtqbSE1sLQQELELMjOUm3WmMxTs3SAGqxACeAEkWClGoYCO7Ynh9Zh3AYFApjiBjnnUAWiyXE3yBUKRWKE3XiE2WyR6oJO8Ru723P2FEHJSz/eGzFGT8cFDGnS7hyMw5gyyN0IqWKgexAL6nE8np8HmdKA%2BeR73umKbJiB2wUqECZIqEppTls/L8ouy6tmuHZdj2fbIoOqhlr%2BoYyvePImAArFYJHunBjpxs6CZlqmDFgZWHocIstCcCRvB%2BBwWikKgnBuNY1jnssqylmYuw8KQBCaKxiwANYgLskgvGYXAaCRJ6SSRXLxAAnJIXL6JwkhcbJfGcLwNwaNJsmLHAsBIMCSR0LE5CUM5rlxMAXBqXwdAELENwQFE5lRKEDT1pwUnAmwggAPIMLQUU8bwWBIkY4ipaQ%2BDENUjg9jc2WCtUXiBdFvBQR05kilEjxLh4WDmQQm4sBVixUAYwAKDWeCYE88VJIwFUyIIIhiOwUijfIShqOZuhtAYRgoEJlj6HgUQ3JAiyoDaGRFQAtI%2BuruqYljWGYvFVDiLgMO4ngtHowShAMpRDG0KRpIS4ytHkX0ZDMgzlO0nS1KMTQPRMIP5WD0wvbM722ODP3DODgNveUiwKKJax6C1mDrDwbEcWZ2X8RwqjxBGB0RpIxzAMgyDHL5LxcMcECCeda3HLghAkKcEltMcHgtl5AuSfMvAyal8wKSAJEvLpBlcrsEbxJIakaSeJHGRwpmkNxvHk1ZIA2dLWj2TAiAgMsVxle5ECefQxBgmwnCU9TtP04zzNmKzvC9nzm5Pm0/BjaI4hTWHM0qOo2ULaQTyPEk7W65xBvmeT8VlUkZXHKgVDHB7NN0wzTMs2zHOoKLzvi1wku2TLcvqS8mkRtpSuGar8S7Lr%2BuG7wxu2KbjcW6QDnW2gWC88yDs0PQzBu9wvDR%2BNkfSNHiix/NuRLcYq02NdhK3fd2R%2BAEz3FEDCR/QUmSQ%2Bft%2BEujcwVNDOI9GMD%2B5EfsONC/71KjI2/gEKY/94bXwqFjHG6wUwSXRF4E4ZwLhXBuPcR4rx3gFi%2BD8WIaBBAAiBNXUE4JUhYgJBkBESIUTEDRLCDE5CcR4iZJQ4kpJyQQSpC1HMEpfSHjvPBfkgphSinFPhfhhE5QKiVAwVU6otQsIELqA0RoTTzDtJeGiLp6LfgQrwkMEiAz7j4f%2BY8p4IyaPjF%2BT0EEmIpi4TSOko5xzEGLEoaxupKwOJ4chZsqF2wbi3FhAcQ4Rz5kLK4yc9FpzCLnOKXxK42zrgwtuXcxiDGmPvCeSM55LG0VCbeQiD4CBPhAC%2BN8H4PQeJ/AeTJgE7yeNAhWexWwoLHBggwOC0S9FIQbH41cASUnBJwnhWpQF6JkVIpRPJ2jiLJnmc02x7pWJp1JkbASB8RIrDWOLMwUs7JyzMHpF4Xc1Ya3Um3XYAR2J6zWYPSyw8zZ2XHlbCATlq4uWdg7J2QwfJ%2BXnoFYgwVQrZXCswJcI1YoAkSslcy6VDDACyrxXKMNCrmRKsgMqhNKoEJubxWq9V6yNXWLxFqeA2rLw6l1HqfUBpDW4lJVeEdJob1kFvOa8dd4IpWlzGwtUtqmj4ntAQh1jq7FOgfS6VkOgw2cBAVwKM2iX1eq/J%2BGRFVqsKBAjGwwZUf2AWfXVoNuho21aqsBENDWTFNVfHV9cljbPYAEfG2LiYcHTgPCyFMqYl29uXP2ldOZWG5jPfmewAjCw%2BWLcNDdzZyVIIpS6fc7lepNk8puus9kZzJg8uNstSA9iBRkEAkggA%3D)

**Comment by MBkkt** [comment]
[Example](https://github.com/arangodb/arangodb/blob/devel/arangod/RestHandler/RestReplicationHandler.cpp#L3530) of the real usage:
Some object that will be stored as ptr to virtual base class, also contains CallbackGuard that contains noexcept functor

**Comment by Naios** [comment]
@MBkkt I'm not nitpicking. The naming of identifiers is not truly relevant in this example, the indirection however is. If you remove the additional indirections, your problem is instantly visible:

```cpp
#include "https://raw.githubusercontent.com/Naios/function2/master/include/function2/function2.hpp"

struct FunctorStorage {
  explicit FunctorStorage(fu2::unique_function<void() noexcept>) noexcept {}
  explicit FunctorStorage(FunctorStorage&&) noexcept {}
};

int main() {
    FunctorStorage* fn = nullptr;
    FunctorStorage impl{std::move(*fn)};
    return 0;
}
```
It seems like there is something wrong with the SFINAE guarding the constructor which works without noexcept but not with noexcept specified.

Until this gets fixed you can use a tag to differenciate between your constructors:

```cpp
#include "https://raw.githubusercontent.com/Naios/function2/master/include/function2/function2.hpp"

struct Tag { };

struct FunctorStorage {
  explicit FunctorStorage(Tag, fu2::unique_function<void() noexcept>) noexcept {}
  explicit FunctorStorage(FunctorStorage&&) noexcept {}
};

struct Base {};

struct Impl : Base {
  explicit Impl(FunctorStorage&& s) noexcept : storage{std::move(s)} {}
  FunctorStorage storage;
};

int main() {
    Impl impl{FunctorStorage{Tag{}, []() noexcept { }}};
    return 0;
}
```

**Comment by MBkkt** [comment]
@Naios Btw fix is easy:

```C++
template<typename Trait, typename T, bool Callable>
struct is_noexcept_correct_lazy {
  static constexpr bool value = invocation::is_noexcept_correct<
                        Trait::is_noexcept::value,
                        typename Trait::template callable<T>,
                        typename Trait::arguments>::value;
};

template<typename Trait, typename T>
struct is_noexcept_correct_lazy<Trait, T, false> {
  static constexpr bool value = false;
};

/// Deduces to a true_type if the type T provides the given signature and the
/// signature is noexcept correct callable.
template <typename T, typename Signature,
          typename Trait =
              type_erasure::invocation_table::function_trait<Signature>>
struct accepts_one
    : std::integral_constant<
          bool, is_noexcept_correct_lazy<Trait, T,
           invocation::can_invoke<typename Trait::template callable<T>,
                                  typename Trait::arguments>::value
                                  >::value> {};
```

**Comment by MBkkt** [comment]
Or
```C++
template <typename T, typename Signature,
          typename Trait =
              type_erasure::invocation_table::function_trait<Signature>>
struct accepts_one
    : std::conjunction<invocation::can_invoke<typename Trait::template callable<T>,
                                       typename Trait::arguments>,
                    invocation::is_noexcept_correct<
                        Trait::is_noexcept::value,
                        typename Trait::template callable<T>,
                        typename Trait::arguments>> {};

```

**Comment by Naios** [comment]
Could you PR your first fix that uses `is_noexcept_correct_lazy`? `std::conjunction` is a C++17 feature and cannot be used by the library (although a polyfill could be used). This is probably also a GCC compiler bug (Clang compiles it fine).

**Comment by MBkkt** [comment]
> Could you PR your first fix that uses is_noexcept_correct_lazy?
Ok

> This is probably also a GCC compiler bug (Clang compiles it fine).
I think it's true, it's really strange that it try to substitute to overload with unique_function first instead of move ctor

**Comment by Naios** [comment]
Solved in https://github.com/Naios/function2/pull/51
