### ISSUE TITLE
Undefined std::free, std::abort and std::malloc

### ISSUE THREAD

**Issue by Rajveer86** [Naios/function2#6]
If I do not include cstdlib before including the header file, I receive the following error message for std::free, std::abort and std::malloc:

error : no member named 'abort' in namespace 'std'

Should the header include cstdlib itself?

**Comment by Naios** [comment]
Sorry, I just saw your two issues, I will take care about it in the next days.

Which toolchain/ platform did you used to build the library ([since the travis build passes with all supported toolchains](https://travis-ci.org/Naios/function2))?

**Comment by Naios** [comment]
I added a test case for missing included headers but [I couldn't reproduce your issue](https://travis-ci.org/Naios/function2/builds/111847892).
Could you elaborate more about your used platform and toolchain?

**Comment by Rajveer86** [comment]
Hi,
This happens when trying to compile an Android NDK application. I am using Visual Studio 2015 (with NDK 10e that comes with it), and compiling C++11/C++1y code with Clang (tested with 3.6 and 3.7). I hope this helps!
Thanks,Raj.

Date: Thu, 25 Feb 2016 12:41:11 -0800

**Comment by Naios** [comment]
Alright, i can't reproduce it but you are right, std::abort and the other functions belong to the <cstdlib> header which i need to include.

**Comment by Rajveer86** [comment]
Just confirming that this works fine for me now. Thank you!
