### ISSUE TITLE
Any docs about the custom allocator?

### ISSUE THREAD

**Issue by renzibei** [Naios/function2#60]
Hi! I saw in the readme that custom Allocator is already supported. However, the usage of this in the source code is quite complex. Is there a more intuitive example of how to use it?
Additionally, as hardware updates quickly, are there any new benchmark data available?

Thank you!

**Comment by feverzsj** [comment]
Seems you have to pass the allocator each time you construct or assign a function object.

**Comment by Naios** [comment]
Yes, the allocator can be passed to each method that accepts a callable for type-erasure, this should be self-explaining by any code-completion.
This repository does not maintain benchmarks directly, but benchmarks are available here: https://github.com/jamboree/CxxFunctionBenchmark.
In this case you need to create a separate issue at this repository and request to update the benchmarks,
