### ISSUE TITLE
supports uses-allocator construction

### ISSUE THREAD

**Issue by feverzsj** [Naios/function2#61]
@Naios

[uses-allocator construction](https://en.cppreference.com/w/cpp/memory/uses_allocator#Uses-allocator_construction)

Seems all it needed is specializing `std::uses_allocator<T, Alloc>`.

**Comment by Naios** [comment]
Hi, yes seems like it. Could you provide the specialization through a PR?

A specialization for the class function in `fu2::detail` should be sufficient:

```
template <typename Config, bool IsThrowing, bool HasStrongExceptGuarantee,
          typename... Args>
class function<Config, property<IsThrowing, HasStrongExceptGuarantee, Args...>>
```

**Comment by Naios** [comment]
Fixed in https://github.com/Naios/function2/pull/62
